import streamlit as st

AUTH_ENABLED = False  # 👉 change à True pour réactiver

if AUTH_ENABLED:
    if "authenticated" not in st.session_state or not st.session_state["authenticated"]:
        st.error("🔒 Please login first.")
        st.stop()
else:
    st.session_state["authenticated"] = True

import pandas as pd
import plotly.express as px
import os
import json
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


st.set_page_config(page_title="Dashboard", layout="wide")


def generate_pdf(total_views, total_watch_time, total_revenue, insights, decisions, business_score, qoe_score):
    file_path = "streaming_report.pdf"

    doc = SimpleDocTemplate(file_path, pagesize=letter)
    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.textColor = colors.HexColor("#1F4E79")

    heading_style = styles["Heading2"]
    heading_style.textColor = colors.HexColor("#1F4E79")

    normal_style = styles["Normal"]

    elements = []

    elements.append(Paragraph("Streaming Analytics Executive Report", title_style))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph("OTT Performance • Revenue Intelligence • Executive Summary", normal_style))
    elements.append(Spacer(1, 25))

    elements.append(Paragraph("KEY PERFORMANCE INDICATORS", heading_style))
    elements.append(Spacer(1, 10))

    kpi_data = [
        ["Metric", "Value"],
        ["TOTAL VIEWS", f"{total_views:,}"],
        ["WATCH TIME MINUTES", f"{total_watch_time:,}"],
        ["REVENUE", f"EUR {total_revenue:,.2f}"],
        ["BUSINESS SCORE", f"{business_score}/100"],
        ["STREAMING QOE SCORE", f"{qoe_score}/100"],
    ]

    table = Table(kpi_data, colWidths=[260, 180])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F4F8FB")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D9E2EC")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ("PADDING", (0, 0), (-1, -1), 10),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 25))

    elements.append(Paragraph("EXECUTIVE INSIGHTS", heading_style))
    elements.append(Spacer(1, 10))

    for insight in insights:
        elements.append(Paragraph(f"- {insight}", normal_style))
        elements.append(Spacer(1, 6))

    elements.append(Spacer(1, 25))

    elements.append(Paragraph("RECOMMENDED ACTIONS", heading_style))
    elements.append(Spacer(1, 10))

    for decision in decisions:
        elements.append(Paragraph(f"- {decision}", normal_style))
        elements.append(Spacer(1, 6))

    elements.append(Spacer(1, 30))

    footer_data = [["Generated by Streaming Analytics SaaS", "Confidential Executive Report"]]
    footer_table = Table(footer_data, colWidths=[260, 180])
    footer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EEF3F8")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#1F4E79")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    elements.append(footer_table)
    doc.build(elements)
    return file_path


def generate_insights(filtered_df, total_views, total_revenue, total_watch_time):
    insights = []

    if filtered_df.empty:
        return ["No data available for the selected filters."]

    if "country" in filtered_df.columns and total_revenue > 0:
        country_revenue = filtered_df.groupby("country")["revenue"].sum()
        top_country = country_revenue.idxmax()
        revenue_share = (country_revenue.max() / total_revenue) * 100
        insights.append(f"{top_country} generates {revenue_share:.1f}% of total revenue.")

        if revenue_share > 50:
            insights.append(f"Recommendation: Focus growth and marketing efforts on {top_country}.")

    if "platform" in filtered_df.columns and total_views > 0:
        platform_views = filtered_df.groupby("platform")["views"].sum()
        top_platform = platform_views.idxmax()
        platform_share = (platform_views.max() / total_views) * 100
        insights.append(f"{top_platform} is the leading device/platform with {platform_share:.1f}% of total views.")

        if platform_share > 50:
            insights.append(f"Recommendation: Prioritize user experience optimization on {top_platform}.")

    if "content_title" in filtered_df.columns and total_views > 0:
        content_views = filtered_df.groupby("content_title")["views"].sum()
        top_content = content_views.idxmax()
        content_share = (content_views.max() / total_views) * 100
        insights.append(f"{top_content} is the top-performing content with {content_share:.1f}% of total views.")

        if content_share > 40:
            insights.append(f"Recommendation: Promote {top_content} to maximize engagement.")

    if total_views > 0:
        revenue_per_view = total_revenue / total_views
        insights.append(f"Average revenue per view is EUR {revenue_per_view:.2f}.")

    if total_views > 0 and total_watch_time > 0:
        avg_watch_time = total_watch_time / total_views
        insights.append(f"Average watch time per view is {avg_watch_time:.1f} minutes.")

        if avg_watch_time < 10:
            insights.append("Alert: Average watch time is low. Review content engagement and playback experience.")

    if "buffering_ratio" in filtered_df.columns:
        avg_buffering = filtered_df["buffering_ratio"].mean()
        if avg_buffering > 0.2:
            insights.append(f"Alert: High buffering detected. Average buffering ratio is {avg_buffering:.2f}.")

    if "startup_time_ms" in filtered_df.columns:
        avg_startup = filtered_df["startup_time_ms"].mean()
        if avg_startup > 4000:
            insights.append(f"Alert: High startup time detected. Average startup time is {avg_startup:.0f} ms.")

    if "error_code" in filtered_df.columns:
        error_rate = filtered_df["error_code"].notna().mean() * 100
        if error_rate > 20:
            insights.append(f"Alert: High error rate detected ({error_rate:.1f}%). Investigate delivery pipeline.")

    if total_revenue < 200:
        insights.append("Alert: Revenue is below target. Consider optimizing monetization strategy.")

    if total_views < 500:
        insights.append("Alert: Engagement is low. Consider promoting stronger content or improving acquisition.")

    return insights


def compute_qoe_score(filtered_df):
    score = 100

    if filtered_df.empty:
        return 0

    if "buffering_ratio" in filtered_df.columns:
        avg_buffering = filtered_df["buffering_ratio"].mean()
        score -= avg_buffering * 100

    if "startup_time_ms" in filtered_df.columns:
        avg_startup = filtered_df["startup_time_ms"].mean()
        if avg_startup > 2000:
            score -= min((avg_startup - 2000) / 100, 30)

    if "error_code" in filtered_df.columns:
        error_rate = filtered_df["error_code"].notna().mean()
        score -= error_rate * 40

    return max(0, min(100, int(score)))


def compute_business_score(total_views, total_revenue, total_watch_time):
    score = 50

    if total_views > 1000:
        score += 15

    if total_revenue > 300:
        score += 20

    if total_views > 0:
        avg_watch_time = total_watch_time / total_views
        if avg_watch_time > 20:
            score += 15

    return max(0, min(100, int(score)))


def generate_decisions(filtered_df, total_views, total_revenue, total_watch_time):
    decisions = []

    if filtered_df.empty:
        return ["No decision available because no data is selected."]

    if total_views > 0:
        revenue_per_view = total_revenue / total_views
        industry_avg = 0.35

        if revenue_per_view < industry_avg:
            decisions.append(
                f"Priority: Revenue per view is below benchmark EUR {industry_avg:.2f}. Review monetization strategy."
            )
        else:
            decisions.append(
                "Opportunity: Revenue per view is above benchmark. Scale current monetization strategy."
            )

    if "country" in filtered_df.columns and total_revenue > 0:
        country_revenue = filtered_df.groupby("country")["revenue"].sum()
        top_country = country_revenue.idxmax()
        country_share = (country_revenue.max() / total_revenue) * 100

        if country_share > 50:
            decisions.append(f"Action: Prioritize marketing and partnership efforts in {top_country}.")

    if "platform" in filtered_df.columns and total_views > 0:
        platform_views = filtered_df.groupby("platform")["views"].sum()
        top_platform = platform_views.idxmax()
        platform_share = (platform_views.max() / total_views) * 100

        if platform_share > 50:
            decisions.append(f"Action: Optimize UX and playback quality for {top_platform} users.")

    if "content_title" in filtered_df.columns and total_views > 0:
        content_views = filtered_df.groupby("content_title")["views"].sum()
        top_content = content_views.idxmax()
        content_share = (content_views.max() / total_views) * 100

        if content_share > 35:
            decisions.append(f"Action: Promote {top_content} in campaigns and homepage highlights.")

    if "buffering_ratio" in filtered_df.columns:
        avg_buffering = filtered_df["buffering_ratio"].mean()
        if avg_buffering > 0.2:
            decisions.append("Urgent: High buffering detected. Investigate CDN, ISP routing or player performance.")

    if "startup_time_ms" in filtered_df.columns:
        avg_startup = filtered_df["startup_time_ms"].mean()
        if avg_startup > 4000:
            decisions.append("Urgent: Startup time is too high. Users may abandon playback before content starts.")

    if "error_code" in filtered_df.columns:
        error_rate = filtered_df["error_code"].notna().mean() * 100
        if error_rate > 20:
            decisions.append(f"Urgent: Error rate is high at {error_rate:.1f}%. Investigate delivery pipeline.")

    return decisions


st.title("📊 Streaming Analytics PRO Dashboard")

current_plan = st.session_state.get("plan", "free")
st.sidebar.info(f"Current plan: {current_plan.upper()}")

sample_path = "sample_data/sample_streaming_data.csv"

if os.path.exists(sample_path):
    with open(sample_path, "rb") as file:
        st.download_button(
            label="⬇️ Download sample CSV",
            data=file,
            file_name="sample_streaming_data.csv",
            mime="text/csv"
        )

uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file is None:
    st.info("👆 Upload a CSV file to start analysis")
    st.stop()

df = pd.read_csv(uploaded_file)
df.columns = df.columns.str.strip().str.lower()

st.success("CSV uploaded successfully!")

st.subheader("Data Preview")
st.dataframe(df, use_container_width=True)

required_columns = ["views", "watch_time_minutes", "revenue"]
missing_columns = [col for col in required_columns if col not in df.columns]

if missing_columns:
    st.error(f"Missing required columns: {missing_columns}")
    st.write("Detected columns:", list(df.columns))
    st.stop()

st.sidebar.header("Filters")

filtered_df = df.copy()

if "country" in df.columns:
    countries = st.sidebar.multiselect(
        "Select country",
        options=sorted(df["country"].dropna().unique()),
        default=sorted(df["country"].dropna().unique())
    )
    filtered_df = filtered_df[filtered_df["country"].isin(countries)]

if "platform" in df.columns:
    platforms = st.sidebar.multiselect(
        "Select device / platform",
        options=sorted(df["platform"].dropna().unique()),
        default=sorted(df["platform"].dropna().unique())
    )
    filtered_df = filtered_df[filtered_df["platform"].isin(platforms)]

if "content_title" in df.columns:
    contents = st.sidebar.multiselect(
        "Select content",
        options=sorted(df["content_title"].dropna().unique()),
        default=sorted(df["content_title"].dropna().unique())
    )
    filtered_df = filtered_df[filtered_df["content_title"].isin(contents)]

total_views = filtered_df["views"].sum()
total_watch_time = filtered_df["watch_time_minutes"].sum()
total_revenue = filtered_df["revenue"].sum()

business_score = compute_business_score(total_views, total_revenue, total_watch_time)
qoe_score = compute_qoe_score(filtered_df)
insights = generate_insights(filtered_df, total_views, total_revenue, total_watch_time)
decisions = generate_decisions(filtered_df, total_views, total_revenue, total_watch_time)

st.markdown("## Key Metrics Overview")

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Total Views", f"{total_views:,}")
col2.metric("Watch Time", f"{total_watch_time:,}")
col3.metric("Revenue", f"€{total_revenue:,.2f}")
col4.metric("Business Score", f"{business_score}/100")
col5.metric("QoE Score", f"{qoe_score}/100")

st.subheader("🧠 Executive Insights")

for insight in insights:
    if insight.startswith("Alert"):
        st.warning(insight)
    elif insight.startswith("Recommendation"):
        st.success(insight)
    else:
        st.info(insight)

st.divider()

st.subheader("🧠 Executive Decision Engine")
st.markdown("### Recommended Actions")

for decision in decisions:
    if decision.startswith("Urgent"):
        st.error(decision)
    elif decision.startswith("Priority"):
        st.warning(decision)
    else:
        st.success(decision)

st.divider()

st.subheader("💾 Save Analysis")

if current_plan == "pro":
    if st.button("Save Analysis"):
        os.makedirs("storage", exist_ok=True)

        history_item = {
            "saved_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "user": st.session_state.get("username", "unknown"),
            "total_views": int(total_views),
            "total_watch_time_minutes": int(total_watch_time),
            "total_revenue": float(total_revenue),
            "business_score": int(business_score),
            "qoe_score": int(qoe_score),
            "insights": insights,
            "decisions": decisions
        }

        username = st.session_state.get("username", "unknown")
        file_path = f"storage/history_{username}.json"

        try:
            with open(file_path, "r") as file:
                history_data = json.load(file)
        except FileNotFoundError:
            history_data = []

        history_data.append(history_item)

        with open(file_path, "w") as file:
            json.dump(history_data, file, indent=2)

        st.success("Analysis saved successfully!")
else:
    st.warning("🔒 Save Analysis is a Pro feature. Upgrade to Pro to save your reports.")

st.subheader("📄 Export Report")

if current_plan == "pro":
    if st.button("📄 Export Executive Report"):
        pdf_file = generate_pdf(
            total_views,
            total_watch_time,
            total_revenue,
            insights,
            decisions,
            business_score,
            qoe_score
        )

        with open(pdf_file, "rb") as file:
            st.download_button(
                label="Download PDF",
                data=file,
                file_name="streaming_report.pdf",
                mime="application/pdf"
            )
else:
    st.warning("🔒 Export PDF is a Pro feature. Upgrade to Pro to download reports.")

st.divider()

if "platform" in filtered_df.columns:
    st.subheader("Views by Device / Platform")
    platform_df = filtered_df.groupby("platform", as_index=False)["views"].sum()
    fig_platform = px.bar(platform_df, x="platform", y="views", title="Views by Device / Platform")
    st.plotly_chart(fig_platform, use_container_width=True)

if "country" in filtered_df.columns:
    st.subheader("Revenue by Country")
    country_df = filtered_df.groupby("country", as_index=False)["revenue"].sum()
    fig_country = px.pie(country_df, names="country", values="revenue", title="Revenue by Country")
    st.plotly_chart(fig_country, use_container_width=True)

if "content_title" in filtered_df.columns:
    st.subheader("Top Content by Views")
    top_content = (
        filtered_df.groupby("content_title", as_index=False)["views"]
        .sum()
        .sort_values(by="views", ascending=False)
    )
    fig_content = px.bar(top_content, x="content_title", y="views", title="Top Content by Views")
    st.plotly_chart(fig_content, use_container_width=True)
    st.dataframe(top_content, use_container_width=True)

if "date" in filtered_df.columns:
    st.subheader("Views Evolution Over Time")
    filtered_df["date"] = pd.to_datetime(filtered_df["date"], errors="coerce")
    time_df = filtered_df.groupby("date", as_index=False)["views"].sum()
    fig_time = px.line(time_df, x="date", y="views", title="Views Over Time")
    st.plotly_chart(fig_time, use_container_width=True)

if "error_code" in filtered_df.columns:
    st.subheader("Errors by Type")
    error_df = (
        filtered_df[filtered_df["error_code"].notna()]
        .groupby("error_code", as_index=False)
        .size()
        .rename(columns={"size": "count"})
    )

    if not error_df.empty:
        fig_errors = px.bar(error_df, x="error_code", y="count", title="Errors by Type")
        st.plotly_chart(fig_errors, use_container_width=True)
    else:
        st.success("No errors detected in the selected data.")

if "buffering_ratio" in filtered_df.columns and "country" in filtered_df.columns:
    st.subheader("Average Buffering by Country")
    buffering_df = filtered_df.groupby("country", as_index=False)["buffering_ratio"].mean()
    fig_buffering = px.bar(
        buffering_df,
        x="country",
        y="buffering_ratio",
        title="Average Buffering Ratio by Country"
    )
    st.plotly_chart(fig_buffering, use_container_width=True)