import streamlit as st

if "authentication_status" not in st.session_state or not st.session_state["authentication_status"]:
    st.warning("Please login from the home page.")
    st.stop()

import pandas as pd
import plotly.express as px
import os
import json
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


st.set_page_config(page_title="Dashboard", layout="wide")


def generate_pdf(total_views, total_watch_time, total_revenue, insights):
    file_path = "streaming_report.pdf"

    doc = SimpleDocTemplate(file_path, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Streaming Analytics Executive Report", styles["Title"]))
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("Key Performance Indicators", styles["Heading2"]))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Total Views: {total_views:,}", styles["Normal"]))
    elements.append(Paragraph(f"Watch Time Minutes: {total_watch_time:,}", styles["Normal"]))
    elements.append(Paragraph(f"Revenue: €{total_revenue:,.2f}", styles["Normal"]))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Executive Insights", styles["Heading2"]))
    elements.append(Spacer(1, 10))

    for insight in insights:
        elements.append(Paragraph(f"- {insight}", styles["Normal"]))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by Streaming Analytics SaaS", styles["Italic"]))

    doc.build(elements)
    return file_path


def generate_insights(filtered_df, total_views, total_revenue):
    insights = []

    if filtered_df.empty:
        return ["No data available for the selected filters."]

    if "country" in filtered_df.columns and total_revenue > 0:
        country_revenue = filtered_df.groupby("country")["revenue"].sum()
        top_country = country_revenue.idxmax()
        revenue_share = (country_revenue.max() / total_revenue) * 100
        insights.append(f"{top_country} generates {revenue_share:.1f}% of total revenue.")

    if "platform" in filtered_df.columns and total_views > 0:
        platform_views = filtered_df.groupby("platform")["views"].sum()
        top_platform = platform_views.idxmax()
        platform_share = (platform_views.max() / total_views) * 100
        insights.append(f"{top_platform} is the leading device/platform with {platform_share:.1f}% of total views.")

    if "content_title" in filtered_df.columns and total_views > 0:
        content_views = filtered_df.groupby("content_title")["views"].sum()
        top_content = content_views.idxmax()
        content_share = (content_views.max() / total_views) * 100
        insights.append(f"{top_content} is the top-performing content with {content_share:.1f}% of total views.")

    if total_views > 0:
        revenue_per_view = total_revenue / total_views
        insights.append(f"Average revenue per view is €{revenue_per_view:.2f}.")

    return insights


st.title("📊 Streaming Analytics PRO Dashboard")

current_plan = st.session_state.get("plan", "free")
st.sidebar.info(f"Current plan: {current_plan.upper()}")

sample_path = "sample_data/sample_streaming_data.csv"

if os.path.exists(sample_path):
    with open(sample_path, "rb") as file:
        st.download_button(
            label="⬇️ Download sample CSV",
            data=file,
            file_name="sample_streaming_data.csv",
            mime="text/csv"
        )

uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file is None:
    st.info("👆 Upload a CSV file to start analysis")
    st.stop()

df = pd.read_csv(uploaded_file)
df.columns = df.columns.str.strip().str.lower()

st.success("CSV uploaded successfully!")

st.subheader("Data Preview")
st.dataframe(df, use_container_width=True)

required_columns = ["views", "watch_time_minutes", "revenue"]
missing_columns = [col for col in required_columns if col not in df.columns]

if missing_columns:
    st.error(f"Missing required columns: {missing_columns}")
    st.write("Detected columns:", list(df.columns))
    st.stop()

st.sidebar.header("Filters")

filtered_df = df.copy()

if "country" in df.columns:
    countries = st.sidebar.multiselect(
        "Select country",
        options=sorted(df["country"].dropna().unique()),
        default=sorted(df["country"].dropna().unique())
    )
    filtered_df = filtered_df[filtered_df["country"].isin(countries)]

if "platform" in df.columns:
    platforms = st.sidebar.multiselect(
        "Select device / platform",
        options=sorted(df["platform"].dropna().unique()),
        default=sorted(df["platform"].dropna().unique())
    )
    filtered_df = filtered_df[filtered_df["platform"].isin(platforms)]

if "content_title" in df.columns:
    contents = st.sidebar.multiselect(
        "Select content",
        options=sorted(df["content_title"].dropna().unique()),
        default=sorted(df["content_title"].dropna().unique())
    )
    filtered_df = filtered_df[filtered_df["content_title"].isin(contents)]

total_views = filtered_df["views"].sum()
total_watch_time = filtered_df["watch_time_minutes"].sum()
total_revenue = filtered_df["revenue"].sum()

col1, col2, col3 = st.columns(3)
col1.metric("Total Views", f"{total_views:,}")
col2.metric("Watch Time Minutes", f"{total_watch_time:,}")
col3.metric("Revenue", f"€{total_revenue:,.2f}")

st.subheader("🧠 Executive Insights")
insights = generate_insights(filtered_df, total_views, total_revenue)

for insight in insights:
    st.info(insight)

st.divider()

st.subheader("💾 Save Analysis")

if current_plan == "pro":
    if st.button("Save Analysis"):
        os.makedirs("storage", exist_ok=True)

        history_item = {
            "saved_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "user": st.session_state.get("username", "unknown"),
            "total_views": int(total_views),
            "total_watch_time_minutes": int(total_watch_time),
            "total_revenue": float(total_revenue),
            "insights": insights
        }

        username = st.session_state.get("username", "unknown")
        file_path = f"storage/history_{username}.json"

        try:
            with open(file_path, "r") as file:
                history_data = json.load(file)
        except FileNotFoundError:
            history_data = []

        history_data.append(history_item)

        with open(file_path, "w") as file:
            json.dump(history_data, file, indent=2)

        st.success("Analysis saved successfully!")
else:
    st.warning("🔒 Save Analysis is a Pro feature. Upgrade to Pro to save your reports.")

st.subheader("📄 Export Report")

if current_plan == "pro":
    if st.button("📄 Export Executive Report"):
        pdf_file = generate_pdf(total_views, total_watch_time, total_revenue, insights)

        with open(pdf_file, "rb") as file:
            st.download_button(
                label="Download PDF",
                data=file,
                file_name="streaming_report.pdf",
                mime="application/pdf"
            )
else:
    st.warning("🔒 Export PDF is a Pro feature. Upgrade to Pro to download reports.")

st.divider()

if "platform" in filtered_df.columns:
    st.subheader("Views by Device / Platform")
    platform_df = filtered_df.groupby("platform", as_index=False)["views"].sum()
    fig_platform = px.bar(platform_df, x="platform", y="views", title="Views by Device / Platform")
    st.plotly_chart(fig_platform, use_container_width=True)

if "country" in filtered_df.columns:
    st.subheader("Revenue by Country")
    country_df = filtered_df.groupby("country", as_index=False)["revenue"].sum()
    fig_country = px.pie(country_df, names="country", values="revenue", title="Revenue by Country")
    st.plotly_chart(fig_country, use_container_width=True)

if "content_title" in filtered_df.columns:
    st.subheader("Top Content by Views")
    top_content = (
        filtered_df.groupby("content_title", as_index=False)["views"]
        .sum()
        .sort_values(by="views", ascending=False)
    )
    fig_content = px.bar(top_content, x="content_title", y="views", title="Top Content by Views")
    st.plotly_chart(fig_content, use_container_width=True)
    st.dataframe(top_content, use_container_width=True)

if "date" in filtered_df.columns:
    st.subheader("Views Evolution Over Time")
    filtered_df["date"] = pd.to_datetime(filtered_df["date"], errors="coerce")
    time_df = filtered_df.groupby("date", as_index=False)["views"].sum()
    fig_time = px.line(time_df, x="date", y="views", title="Views Over Time")
    st.plotly_chart(fig_time, use_container_width=True)